import { calculateSalary } from "@/lib/calculations/salary";
import { formatGHS } from "@/lib/money";

/** A worked example generated by the real engine at build time, so content never drifts from the calculator. */
export function WorkedExample({ basicCedis, allowancesCedis = 0 }: { basicCedis: number; allowancesCedis?: number }) {
  const r = calculateSalary({ basicSalary: basicCedis * 100, allowances: allowancesCedis * 100, frequency: "monthly" });
  const m = r.monthly;
  const steps: [string, string][] = [
    ["Basic salary", formatGHS(m.basicSalary)],
    ...(m.allowances > 0 ? ([["+ Taxable allowances", formatGHS(m.allowances)]] as [string, string][]) : []),
    ["= Gross salary", formatGHS(m.gross)],
    [`− SSNIT (${r.ssnit.rateBp / 100}% of basic)`, formatGHS(m.ssnit)],
    ["= Taxable income", formatGHS(m.taxableIncome)],
    ["− PAYE on taxable income", formatGHS(m.paye)],
    ["= Estimated take-home pay", formatGHS(m.net)],
  ];
  return (
    <figure className="not-prose my-6 rounded-xl border border-border bg-surface p-4">
      <figcaption className="mb-3 text-sm font-semibold">
        Worked example: {formatGHS(m.gross)} a month ({r.ruleset.label} rules)
      </figcaption>
      <dl className="text-sm tabular-nums">
        {steps.map(([label, value]) => (
          <div key={label} className={`flex justify-between gap-4 py-1 ${label.startsWith("=") ? "border-t border-border font-semibold" : ""}`}>
            <dt>{label}</dt>
            <dd>{value}</dd>
          </div>
        ))}
      </dl>
      <p className="mt-3 text-xs text-muted">
        PAYE detail:{" "}
        {r.paye.bands
          .filter((b) => b.taxableInBand > 0)
          .map((b) => `${formatGHS(b.taxableInBand)} × ${b.rateBp / 100}%`)
          .join(" + ")}{" "}
        = {formatGHS(m.paye)}
      </p>
    </figure>
  );
}
